### ISSUE TITLE
Feature: User can draw on the web page canvas

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/napkinnotes#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can draw on the web page canvas.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking and dragging the mouse on the canvas will draw a freeform line that matches the path the mouse moves until the mouse button is raised.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature1_Desktop](https://user-images.githubusercontent.com/21215658/180862973-e5344e6c-25de-4eb2-9ff1-2aa89bdd1d65.PNG)
![Feature1_Mobile](https://user-images.githubusercontent.com/21215658/180862974-1f721266-f130-40dd-b7d9-98127454b531.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

(These were already done in included codebase)
- [x] ~Update `server/index.js` to start a standard Express server~
- [x] ~Add in error handling middleware~
- [x] ~Add in conditional development middleware~
- [x] ~Add static file serving with `express.static()` and `__dirname`~

### ⚡ Client Tasks

- [x] Create a component to render an SVG canvas
- [x] Create a logo component that renders on the canvas until a user starts drawing
- [x] Create a component to render user drawn lines (`path` element)
- [x] Modify cursor over SVG canvas to indicate that user can draw (custom or built-in CSS style)
- [x] Add method to create a drawn line upon mouse down
- [x] Add method to continuously update line upon mouse move
- [x] Add method to stop drawing line upon mouse up

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that one and only one `path` element is created for each mousedown-mousemove-mouseup combination.
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
