### ISSUE TITLE
Feature: User can erase drawings

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/napkinnotes#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can erase drawings.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can toggle between an eraser tool and a pen tool. When the eraser tool is selected, clicking or dragging the mouse across a drawn element deletes it from the canvas.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature2_Desktop](https://user-images.githubusercontent.com/21215658/181343038-a6977101-0447-4f76-a048-fe21dabac13b.PNG)
![Feature2_Mobile](https://user-images.githubusercontent.com/21215658/181343040-334ebff9-626b-4501-96df-d859414d356a.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to for a toolbar
- [x] ~Create a component for buttons on toolbar (in this feature, just Pencil and Eraser buttons)~ Not necessary, may not be a generalizable pattern
- [x] Have toolbar contain two connected buttons
- [x] Have toolbar positioned `fixed` on the page
- [x] Check toolbar positioning on mobile works properly
- [x] Update SVG Canvas component to have state for drawing or erasing
- [x] Add method to Home component class that sets the state given an input
- [x] Have button clicks set the Drawing or Erasing state with visual changes (making button "selected")
- [x] Update SVG Canvas component to check if drawing or erasing is happening on mouse/touch handlers
- [x] Write erase functionality
  - [x] Attach an `elementId` data attribute to each path to uniquely identify them
  - [x] If state is Erase and user drags over a drawn path, log the path's ~`key`~ `elementId` to the console
  - [x] Update functionality to remove that path from `drawnPaths`

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
  - Caveat: Event listeners are listening/querying to the DOM directly, but not _manipulating_ directly
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennisliu9** [comment]
When using the eraser tool, fast mouse movements can cause the eraser to "skip over" drawn paths. `mouseover` event needs to capture the mouse location on the path, and fast movements can cause the mouse to skip over the pixels occupied by the path.

**Comment by dennisliu9** [comment]
View checked on actual mobile device, icon placement looks good
