### ISSUE TITLE
Feature: User can change the color of their pen

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/napkinnotes#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can change the color of their pen for any subsequent drawings.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A button will bring up a color picker where the user can choose what color to draw with. Drawing will reflect that color, and switching colors does not affect elements that are already drawn.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature3_Desktop](https://user-images.githubusercontent.com/21215658/181343158-a5f0c787-4617-4bd7-a05a-054b345b5d7e.PNG)
![Feature3_Mobile](https://user-images.githubusercontent.com/21215658/181343162-c7c852fe-037c-45de-90cb-d415a261dccf.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Contain the toolbar in a [level](https://bulma.io/documentation/layout/level/)
  - [x] Ensure button and drawing functionalities are not changed due to this
- [x] Add a color selection [dropup](https://bulma.io/documentation/components/dropdown/#dropup) to the level
  - [x] For the dropup content, add a horizontal container of circle buttons, each button colored differently (start with 2 or 3 colors)
  - [x] Attach a data attribute to each color circle corresponding to their HEX/HSL/Color representation
- [x] In the Home component
  - [x] add a current color state
  - [x] add a method for setting the color state
  - [x] Pass to the SVG Canvas component the current color as a prop
  - [x] Pass the current color as a prop to the Toolbar component
  - [x] Pass the color setting method to the Toolbar component
- [x] In the SVG Canvas component
  - [x] Set the stroke color to the passed color
- [x] In the Toolbar component
  - [x] Set the circle icon on the dropup trigger to be colored the passed color
  - [x] Create an `onClick` method that toggles a state property on the Toolbar for `isSelectingColor` (Boolean)
  - [x] Modify dropup `className` to contain `is-active` if `isSelectingColor` is `true`
  - [x] Create another `onClick` method for choosing a color that calls the Home passed method for setting a color and then flips Toolbar state property `isSelectingColor` (to close the options)
  - [x] Assign this `onClick` method to each of the color buttons within the dropup's content
- [x] Make the color choices generated from an array of color options
  - [x] Create a component (function) for color options
  - [x] Add array of color options to the Home component's state
  - [x] Have toolbar's dropup content generate the color buttons with a `map` and the colors array passed as a prop

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure color selection dropup closes the color options (dropup content) when one is selected
- [x] Make sure color selection is easy to do on mobile, adjusting size as necessary
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennisliu9** [comment]
In the future, consider making the color selection vertical on mobile via level-items. This may be better if there are more colors. Alternatively, create a scrollable horizontal color selection.
