### ISSUE TITLE
Feature: User can add text on the canvas

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/napkinnotes#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a text box on the canvas and input text.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click the Text tool button. Wherever they click on the screen, there will be a blinking cursor to indicate that they can start typing. The text they type renders on the screen. If they don't type anything, the element is not created.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature4_Desktop](https://user-images.githubusercontent.com/21215658/181343252-4a3ff691-1477-4932-80f7-68f99114d1c1.PNG)
![Feature4_Mobile](https://user-images.githubusercontent.com/21215658/182234949-5e0a9226-272e-403c-baf2-cc8852fa80fc.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Add Text button to Toolbar
- [x] Text button updates the state property `currentTool` to `'text'`
  - [x] Use `this.props.updateCurrentTool`
- [x] Change the canvas cursor to text i-beam cursor when Text is selected (CSS variable + `root.style.setProperty`?)
- [x] Create component for text elements (use [SVG text](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text))
- [x] Add new properties to SVG Canvas state
  - [x] isTyping (initialize to `false`)
  - [x] Revise `drawnPaths` to `elements`
    - [x] Revise all function references and test with just drawing normally
    - [x] Add an additional property to all objects indicating `path` or `text`
    - [x] Text objects should contain the following properties: `elementType` `elementId`, `startingPoint`, `userText`, `fill`, `font-size`
- [x] On mouse click
  - [x] Set the SVG Canvas state property `isTyping` to `true`
  - [x] Capture mouse click/tap coordinates
  - [x] Create starting textbox object
  - [x] Update state with incremented next element ID, populate the current element ID, and add new object to array of text boxes
  - [x] A blinking cursor/some indicator appears at mouse click location
- [x] Write method for if `isTyping` is `true`, register keyboard presses
  - [x] Write method similar to `addCoordinateToPathData` but adding a single character input
    - [x] Figure out injection safety (putting user input into a component is [safe](https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks) but what about into the state? Into SQL?)
- [x] SVG Canvas renders text elements
  - [x] Import the text element component
  - [x] Write a `map` for text elements that is similar to that of `DrawnPath`
- [x] Clicking away should stop the input (set some `isTyping` to `false`)
  - [x] Add conditional to SVG Canvas's onClick handler to check if canvas was clicked ~and current text box __was not__ clicked~ (Just checking for clicks, there is no feature to move the cursor so no need to detect if textbox was clicked)
  - [x] If so, set `isTyping` to `false` and set `currentElementId` back to `null`
  - [x] ~`Ctrl-Enter` may also be a method of marking typing as "done"~ Make Enter and Escape also stop text input
  - [x] If user did not input any text, remove the text object
    - [x] Remove text object when user switches tools before entering text
- [x] Adding text on mobile
  - [x] Create modal with a `textarea` element to take in user input
  - [x] Tapping on screen saves tap location to a variable brings up the modal
  - [x] Add a submit button which populates the textbox object with user input and other properties and adds it to the array of textbox objects in the state
    - [x] ~Prevent default behavior of button click~ Not necessary
    - [x] Submit button should close the modal
  - [x] Add a cancel button which closes the modal without updating the array of textbox objects

### 🧑‍⚕️ Clean Up Tasks

- [x] Ensure erase functionality works on text as expected
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennisliu9** [comment]
> Copy and paste is not supported with any text input
> Despite being a `textarea` element on the mobile modal, multi-line text strings are not supported for any text input
