### ISSUE TITLE
Feature: User can add Markdown text and it will render properly

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/napkinnotes#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can enter text that is written in Markdown format and it will be rendered with styling.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can choose the Markdown Text tool, which functions similarly to the text tool but the content will be interpreted as Markdown and converted into HTML once the user clicks out of the box. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature5_Desktop](https://user-images.githubusercontent.com/21215658/181343339-eeffb75e-cd9d-4bf6-af82-4a3f261eea11.PNG)
![Feature5_Mobile](https://user-images.githubusercontent.com/21215658/181343341-b7dc2cc5-131f-481f-9d51-a142041b19f8.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### Notes
* Consider Markdown text as a separate tool from plain text since they don't share between them (new object structure, new methods, new event handling)

### 🌱 Environment Tasks
- [x] Install Marked, Prism, and DOMPurify as dependencies via npm

#### Toolbar
- [x] Similar to the color selection dropup menu, add a dropup menu for the Text button
  - [x] Dropup should be activated when Toolbar's `state.selectingTextType = true`
  - [x] Within the dropup, add buttons for plain text and Markdown text
  - [x] Selecting one should set a state on the Toolbar component (`textType` = 'text' | 'textMd')
    - [x] Depending on the textType state property, show the correct button with the correct icon in the toolbar
      - [x] (textType should stay in Toolbar, and is only used for displaying the right icon/button)
  - [x] Selecting one should update the `currentTool` state property in the Home component ('text' or 'textMd')
    - [x] reuse the method `updateCurrentTool` from the Home component
  - [x] Selecting one should close the menu (set `state.selectingTextType = false`)
  - [x] Clicking the text/MD button should both show the dropup menu *and* select the tool
    - [x] Selecting a text type from the dropup menu should set the tool and close
    - [x] Clicking any other tool should close the dropup menu
    - [ ] Clicking away from the toolbar should close the dropup menu

#### Canvas
- [x] Prepare SVG Canvas component to handle Markdown boxes
  - [x] Create method that creates an object for Markdown boxes (required params of `foreignObject` elements)
    - [x] x, y, width, length, user input, elementId's, elementType, render
      - [x] `render` is a boolean, and when passed to the MarkdownBox component, determines if a `textarea` is shown or the rendered HTML is shown
    - [x] method should also append to the state's `elements` array
  - [x] Add to mousedown handler for when the current tool is `textMd`
    - [x] Similar to `finishTextWriting`, if the current element (found by ID) has `render=false`, set `render=true` and `currentElementId = null` to effectively set the Markdown element as "done"
    - [x] Apply this functionality to keydown handler, listening for the Escape key
- [x] Handle edge cases for closing dropup menu and submitting
  - [x] When user changes tools in the middle of writing Markdown, it should be treated as submitting Markdown for rendering
    - [x] Should also close dropup selection like plain text tool

#### Markdown Component
- [x] Create component for MarkdownBox
  - [x] (MarkdownBox should handle the calls to Marked/Prism/DOMPurify, take in user input string)
  - [x] Returns a `<foreignObject>` element
    - [x] If `render` (passed prop from SVG Canvas) is false, contains a `<textarea>`
    - [x] As user types into textarea, input gets stored in the specific object for this current MarkdownBox in SVG Canvas's state.elements array (via method as prop)
      - [x] textarea's value is populated by the value in the state (passed as prop)
    - [x] Upon finishing input (SVG Canvas is listening for clicks outside textarea and Escape key)
      - [x] (If textarea's value was empty, remove the foreignObject element)
      - [x] If value was not empty, update the property that was used to indicate first click to now no longer show first click (now `render=true`)
      - [x] If `render=true` (passed as prop) `<textarea>` gets replaced with processed Markdown HTML
      - [x] textarea's value is added to an object that gets stored in SVG Canvas' `elements` state property with a new `elementType` for Markdown (raw input is stored, not the processed HTML!)
  - [x] User click location should be passed as a prop from SVG Canvas to MarkdownBox
  - [x] ~Write method that extracts out `<code>` to pass to Prism~ Not necessary, already handled
  - [x] Write method that takes user input and passes it through Marked, then Prism, then DOMPurify
- [x] Add buttons to Submit/Cancel for textarea on mobile
  - [x] Pass methods props to MarkdownBox componenet
  - [x] Attach methods to buttons

### 🧑‍⚕️ Clean Up Tasks
- [x] Resolve code blocks not being styled by `prism.css`
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
