### ISSUE TITLE
Feature: User can save drawings to their account

### ISSUE THREAD

**Issue by dennisliu9** [dennisliu9/napkinnotes#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a drawing to their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on the Save Drawing button, a link to the current canvas is associated with their account and the canvas with its elements will be persisted to the database. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Feature7_Desktop1](https://user-images.githubusercontent.com/21215658/181344973-a78245bf-464a-4eb1-97ac-da3b99dae376.PNG)
![Feature7_Desktop2](https://user-images.githubusercontent.com/21215658/181344976-f8fb9e88-f677-464b-8d66-f5e57573aeb7.PNG)
![Feature7_Desktop3](https://user-images.githubusercontent.com/21215658/181344978-abe61831-3717-4b5c-93bf-f4ccf31a2b21.PNG)
![Feature7_Mobile1](https://user-images.githubusercontent.com/21215658/181344980-efc1957c-7124-41f8-b972-80e5f9c6f9b8.PNG)
![Feature7_Mobile2](https://user-images.githubusercontent.com/21215658/181344984-812b2738-0e7d-41e6-ac92-4558cefff372.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to swap the `Strokes` and `TextBoxes` table with a JSONB column in `Drawings` that reflects the current data model of `SVGCanvas.state.elements`
- [x] Update `data.sql` to have a test user under `userId = 1`
- [x] Use command `npm run db:import` to create tables based on new schema

### ☁️ Server Tasks

- [x] Update `server/index.js` to have each of the following routes and testing with HTTPie for each
  - [x] a `POST` route that adds a new record to the `Drawings` table and returns the inserted `drawingId`
  - [x] a `GET` route that retrieves the record in `Drawings` for the current `drawingId`
  - [x] a `POST` route that retrieves whether or not the current drawing is marked as "saved" for the current user
    - [x] Needs to be `POST` because data is being sent to the server
  - [x] a `PUT` route that updates the JSON column for the current drawing with the `state.elements` array
    - [x] Output `NOW()` so the app knows when it was last saved/updated
  - [x] a `POST` route that adds a new record to the `DrawingSaves` table with the current `userId` and `drawingId`
  - [x] a `DELETE` route that removes the record from `DrawingSaves` where the record matches on `userId` and `drawingId`
- [x] Handle all errors and respond to the client

### 🌱 Environment Tasks

- [x] Install [react-toastify](https://www.npmjs.com/package/react-toastify) to handle notifications

#### Setting up `Home`

- [x] Add an `isLoading` property to Home's `state` and set to `true`
- [x] Add an `drawingId` property to Home's `state` and set to `null`
- [x] Add a `userId` property to App's `state` and set to `1` (or add to a Context)
- [x]  (`POST`) Write a method that calls a `fetch` that inserts a new record into `Drawings` and returns the inserted `drawingId` 
  - [x] In the method, attach a `then` that sets the `drawingId` property with the response and returns a `Promise.resolve()`
- [x] (`GET`) Write a method to that calls a `fetch` request that retrieves the record in `Drawings` for the value of `state.drawingId`
  - [x] Set the state property `elements` to the equivalent column in the response
  - [ ] (Will there be an issue of `state.drawingId` not being set to the response when the `GET` request gets sent?)
- [x] Write a method that changes Home's `state.isLoading` to `false`
- [x] ~~At the beginning of loading Home, build up an array of these three methods (POST, GET, isLoading change)~~
  - [x] If `drawingId` is `null`, include the POST, otherwise only include the GET and isLoading change
  - [x] ~~Use `Array.prototype.map()` to chain the methods/functions in the array together (something like `previousValue.then(currentValue)`)~~
  - [x] Changed this to use `async/await` for simplicity

#### Control Bar

- [x] Add a control bar to hold the Save button in the top right of the screen
- [x] Add Save button
- [x] Conditionally style the Save button to be grey or black depending on if `userId` is null
- [x] (`POST`) Write a method that sends a `fetch` request to see if the user has saved this drawing
  - [x] If so, conditionally style the Save button to be black or `has-text-primary` (set a state property for if the drawing has been saved)
- [x] (`POST`) Write a method that sends a `fetch` request when the user clicks the Save button and they haven't saved it yet
- [x] (`DELETE`) Write a method that sends a `fetch` request when the user clicks the Save button and they **have** already save it (undoing the save)

#### Canvas

- [x] (`PUT`) Write a method that updates the database with the contents of `state.elements`
- [x] Call this method whenever a new object is added to and whenever an object is removed from `state.elements`

#### Notifications

- [x] ~~Create a file for the toast container component~~
- [x] ~~Configure appearance of toasts via props~~
  - [x] ~~Takes notification type as a prop (error, info, success, etc.)~~
  - [x] ~~Takes notification message as a prop~~
- [x] `react-toastify` is very easy to use, no need to create a separate component or function
  - [x] Add `toast` function to Context for child components to access
- [x] Add toast container as a child to the App component/page
  - [x] (notifications can happen anywhere in our app, not just the Home page)
  - [x] Put the method that triggers a notification into a Context so that all children can easily create notifications

### 📃 Omnibus Tasks
- [x] Add in custom logo to Logo Splash component
  - [x] Add transparency amount to lighten color
- [x] Change favicon to one that matches Logo Splash
- [x] Change textarea font to be monospace for more natural looking Markdown input

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
